<?php

return [

    /*
  |--------------------------------------------------------------------------
  | Filter the following list when this language is used.
  |--------------------------------------------------------------------------
  | Provided by @aletundo
  |
  */

    'affanculo',
    'allupato',
    'ammucchiata',
    'anale',
    'arrapato',
    'arrusa',
    'arruso',
    'assatanato',
    'bagascia',
    'bagassa',
    'baldracca',
    'balle',
    'battona',
    'belino',
    'biga',
    'bocchinara',
    'bocchinaro',
    'bocchino',
    'bofilo',
    'boiata',
    'bordello',
    'brinca',
    'bucaiolo',
    'budiùlo',
    'busone',
    'cacca',
    'caccati in mano e prenditi a schiaffi',
    'caciocappella',
    'cagare',
    'cagata',
    'cagna',
    'cappella',
    'casci',
    'cazzata',
    'cazzi',
    'cazzimma',
    'cazzo',
    'checca',
    'chiappa',
    'chiavare',
    'chiavata',
    'ciospo',
    'ciucciami il cazzo',
    'coglione',
    'coglioni',
    'cornuto',
    'culattina',
    'culattone',
    'culo',
    'di merda',
    'dio bestia',
    'dio cane',
    'dio porco',
    'ditalino',
    'fanculo',
    'fica',
    'figa',
    'figlio di buona donna',
    'figlio di puttana',
    'figone',
    'fottere',
    'fottersi',
    'fracicone',
    'fregna',
    'frocio',
    'froscio',
    'fuori come un balcone',
    'goldone',
    'guardone',
    'incazzarsi',
    'incoglionirsi',
    'inculare',
    'leccaculo',
    'lecchino',
    'lofare',
    'loffa',
    'loffare',
    'mannaggia',
    'merda',
    'merdata',
    'merdoso',
    'mignotta',
    'minchia',
    'minchione',
    'mona',
    'mussa',
    'nerchia',
    'padulo',
    'palle',
    'palloso',
    'patonza',
    'pecorina',
    'picio',
    'pincare',
    'pippone',
    'pipì',
    'pirla',
    'pisciare',
    'piscio',
    'pisello',
    'pistola',
    'pistolotto',
    'pomiciare',
    'pompa',
    'pompinara',
    'pompino',
    'porca madonna',
    'porca miseria',
    'porca puttana',
    'porca',
    'porco dio',
    'porco due',
    'porco zio',
    'potta',
    'puppami',
    'puttana',
    'recchione',
    'ricchione',
    'rincoglionire',
    'rizzarsi',
    'rompiballe',
    'rottinculo',
    'ruffiano',
    'sbattersi',
    'sborra',
    'sborrata',
    'sborrone',
    'sbrodolata',
    'scopare',
    'scopata',
    'scorreggiare',
    'sega',
    'segaiolo',
    'slinguare',
    'slinguata',
    'smandrappata',
    'soccia',
    'socmel',
    'sorca',
    'spompinare',
    'sticchio',
    'stronza',
    'stronzata',
    'stronzo',
    'succhiami',
    'sveltina',
    'sverginare',
    'tarzanello',
    'terrone',
    'testa di cazzo',
    'tette',
    'topa',
    'troia',
    'troietta',
    'troiona',
    'troione',
    'trombare',
    'vacca',
    'vaffanculo',
    'zinne',
    'zio cantante',
    'zoccola',
];
